# This is a syncronisation workflow to that pulls the latest documentation from the lammps repository
# and builds an updated vsix-package based on these files.

name: CI

on:
  push:
#  schedule:
#    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2 
    - uses: actions/setup-node@v1
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Download updated Docs
      run:
        svn export https://github.com/ThFriedrich/lammps/trunk/doc/src rst --force

    - name: Build Docs TS-Object
      run: |
        python3 -m pip install --upgrade pip
        pip3 install numpy
        python3 ./src/rst2JSON.py
        
    - name: Build package
      run: |
        npm install
        npm install -g vsce
        vsce package
        
    - name: Get Tag and Date
      id: date_tag
      run: | 
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=vsix_file::$(find *.vsix)"
        echo "::set-output name=tag::$(find *.vsix | tr -cd '[[0-9.]]' | rev | cut -c2- | rev)"
        
    - name: Create Release
      if: ${{ success() }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DATE: ${{ steps.date_tag.outputs.date }}
        TAG: ${{ steps.date_tag.outputs.tag }}  
      with:
        tag_name: sync-${{ steps.date_tag.outputs.date }}
        release_name: Lammps-${{ steps.date_tag.outputs.tag }} Synchronisation Release - ${{ steps.date_tag.outputs.date }}
        body: Scheduled synchronisation of lammps_vscode-${{ steps.date_tag.outputs.tag }} with Lammps documentation from ${{ steps.date_tag.outputs.date }} 
        draft: false
        prerelease: false   
    
    - name: Archive package
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/${{ steps.date_tag.outputs.vsix_file }}
        name: ${{ steps.date_tag.outputs.vsix_file }}

    - name: Publish package
      if: ${{ success() }}
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ steps.create_release.outputs.id }} 
        args: ${{ steps.date_tag.outputs.vsix_file }}
    
        
        
